import { IconsEnum } from "../../atoms/Icon/IconTypes";

export const hidders = {
    leftHidde: 'before:content-[""] before:h-full before:w-[150px] before:absolute before:left-0 before:top-0 before:bg-gradient-to-r before:from-[#ffffff] before:from-15% before:z-10',
    rightHidde: 'after:content-[""] after:h-full after:w-[150px] after:absolute after:right-0 after:top-0 after:bg-gradient-to-l after:from-[#ffffff] after:from-15%',
}

export const icons = [
    
    'slack',
    'react',
    'vuejs',
    'vitejs',
    'nextjs',
    'storybook',
    'redux',
    'nodejs',
    'express',
    'npm',
    'vscode',
    'figma',
    'typescript',
    'javascript',
    'html5',
    'css3',
    'sass',
    'mui',
    'tailwindcss',
    'bootstrap',
    'git',
    'github',
    'jenkins',
    'jira',
    'bitbucket',
    'confluence',
    'cypress',
    'eslint',
    'fireBase',
    'ggcloud',
    'apache',
    'composer',
    'laravel',
    'java',
    'androidSttudio',
    'mongodb',
    'mysql',
    'sqlite',
    'postgresql',
    'postman',
];

interface StackIcons {
    [key: string]: IconsEnum;
}

export const stackIcons: StackIcons = {
    'react': IconsEnum.react,
    'vuejs': IconsEnum.vuejs,
    'vitejs': IconsEnum.vitejs,
    'nextjs': IconsEnum.nextjs,
    'storybook': IconsEnum.storybook,
    'redux': IconsEnum.redux,
    'nodejs': IconsEnum.nodejs,
    'express': IconsEnum.express,
    'npm': IconsEnum.npm,
    'vscode': IconsEnum.vscode,
    'figma': IconsEnum.figma,
    'typescript': IconsEnum.typescript,
    'javascript': IconsEnum.javascript,
    'html5': IconsEnum.html5,
    'css3': IconsEnum.css3,
    'sass': IconsEnum.sass,
    'mui': IconsEnum.mui,
    'tailwindcss': IconsEnum.tailwindcss,
    'bootstrap': IconsEnum.bootstrap,
    'git': IconsEnum.git,
    'github': IconsEnum.github,
    'jenkins': IconsEnum.jenkins,
    'jira': IconsEnum.jira,
    'bitbucket': IconsEnum.bitbucket,
    'confluence': IconsEnum.confluence,
    'cypress': IconsEnum.cypress,
    'eslint': IconsEnum.eslint,
    'fireBase': IconsEnum.fireBase,
    'ggcloud': IconsEnum.ggcloud,
    'apache': IconsEnum.apache,
    'composer': IconsEnum.composer,
    'laravel': IconsEnum.laravel,
    'java': IconsEnum.java,
    'androidSttudio': IconsEnum.androidSttudio,
    'mongodb': IconsEnum.mongodb,
    'mysql': IconsEnum.mysql,
    'sqlite': IconsEnum.sqlite,
    'postgresql': IconsEnum.postgresql,
    'postman': IconsEnum.postman,
    'slack': IconsEnum.slack,
}
